### PR TITLE
Fix image occlusion note types

### PR DESCRIPTION
**Pull request by RisingOrange**
Previously the script in `clozeOneByOneFront.ejs` assumed that there is a field named "One by one" on the card. 

This script was used on the IO note types too which do not have this field which caused this issue: https://github.com/AnKingMed/anking_notes_addon/issues/7

### CODE REVIEW

**Comment by RisingOrange** [comment]
cc @BlueGreenMagick

**Comment by BlueGreenMagick** [comment]
Looks good!

**Comment by RisingOrange** [comment]
Can you merge this? @AnKingMed

**Comment by AnKingMed** [comment]
Done. Do you not have merge permissions? I'll need to fix that. 

can you go ahead and upload to ankiweb?

**Comment by RisingOrange** [comment]
You mean the note types add-on? I uploaded it already. :)

**Comment by RisingOrange** [comment]
And no, I don't have merge permissions yet

**Comment by AnKingMed** [comment]
I'll fix that right now

**Pull request merged**
